CODE_DIR = ../make-M-cmd2

# 切换到CODE_DIR中去执行make再执行目标modules
# 相当于：make -C ../make-M-cmd2 M=/home/yzq-linux/Desktop/linux_study/make_study/make-M-cmd1 modules
all:
	$(MAKE) -C $(CODE_DIR) M=$(CURDIR) modules